FROM eclipse-temurin:21.0.1_12-jre-ubi9-minimal

RUN rm -rf /etc/localtime && ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime

RUN mkdir -p /opt/inside/script
RUN mkdir -p /opt/inside/application
RUN mkdir -p /opt/inside/logs

WORKDIR /opt/inside/application

COPY ./etc/Docker/application-search/start.sh /opt/inside/script/start.sh
COPY ./server/application-search/target/Inside_DayOffMarkerSearch.jar /opt/inside/application/Inside_DayOffMarkerSearch.jar

RUN chmod +X /opt/inside/script/start.sh
RUN chmod +X /opt/inside/application/Inside_DayOffMarkerSearch.jar

ENTRYPOINT sh /opt/inside/script/start.sh
