version: '2'

networks:
  dayoff_marker:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 250M
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - dayoff_marker
    ports:
      - '6379:6379'
  redis-slave:
    image: 'bitnami/redis:latest'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 250M
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=localhost
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=7000
    ports:
      - '7000:7000'
    depends_on:
      - redis
    networks:
      - dayoff_marker
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 250M
    environment:
      - REDIS_MASTER_HOST=localhost
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
    depends_on:
      - redis
    ports:
      - '26379-26381:26379'
    networks:
      - dayoff_marker