server:
  port: 8080
  servlet:
    context-path: /dayoffmarker

logging:
  exception-conversion-word:
  level:
    liquibase: INFO
    root: INFO

liquibase:
  change-log: classpath:db.changelog-master.yaml

jwt:
  secret: usersecretforjwtauthenticateoratoroeuaroupadoreideromalalalameudeuscomoessabencaodechave
  valid: 60 #Define em Minutos o tempo valido do Token

spring:
  data:
    redis:
      repositories:
        enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: bicDev2021!
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  batch:
    initialize-schema: always
    job:
      enabled: false
  task:
    scheduling:
      pool:
        size: 5
  redis:
    port: 26379
    passowrd: str0ng_passw0rd
    sentinel:
      database: 0
      master: mymaster
      nodes:  localhost
      passowrd: str0ng_passw0rd
  cache:
    type: redis
    edis:
      key-prefix: 'api::'
      time-to-live: 12000000

dayoff-marker-cache:
  config:
    caches:
      -  name: DAYOFF_MARKER_ADMIN
         timeToLiveSeconds: 3600
      -  name: TEN_MINUTES_CACHE
         timeToLiveSeconds: 600

  dayoff-caches:
    caches:
      serviceOne_cache: DAYOFF_MARKER_ADMIN
      serviceTwo_cache: TEN_MINUTES_CACHE

application:
  scheduling:
    request:
      create_date:
        fixedDelayInMilliseconds: 60000
        fixedRateInMilliseconds: 60000
        initialDelayInMilliseconds: 120000

jdempotent:
  enable: true
  cache:
    redis:
      database: 1
      password: "str0ng_passw0rd"
      sentinelHostList: localhost
      sentinelPort: "26379"
      sentinelMasterName: "mymaster"
      expirationTimeHour: 2
      dialTimeoutSecond: 3
      readTimeoutSecond: 3
      writeTimeoutSecond: 3
      maxRetryCount: 3
      expireTimeoutHour: 3
