server:
  port: 8080
  servlet:
    context-path: /dayoffmarker

logging:
  exception-conversion-word:
  level:
    liquibase: INFO
    root: INFO

liquibase:
  change-log: classpath:db.changelog-master.yaml

jwt:
  secret: usersecretforjwtauthenticateoratoroeuaroupadoreideromalalalameudeuscomoessabencaodechave
  valid: 60 #Sets token validity time in minutes

spring:
  data:
    redis:
      repositories:
        enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/DayOff_Marker
    username: dayoff_marker_ADMIN
    password: pe&X=RwN&@!H7%mB
    idleTimeout: 150000
    maxLifetime: 300000
    minimumIdle: 5
    maximumPoolSize: 25
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  batch:
    initialize-schema: always
    job:
      enabled: false
  task:
    scheduling:
      pool:
        size: 5
  redis:
    port: 26379
    passowrd: str0ng_passw0rd
    sentinel:
      database: 0
      master: mymaster
      nodes:  localhost
      passowrd: str0ng_passw0rd
  cache:
    type: redis
    edis:
      key-prefix: 'api::'
      time-to-live: 12000000

dayoff-marker-cache:
  config:
    caches:
      -  name: DAYOFF_MARKER_CITY
         timeToLiveSeconds: 3600
      -  name: DAYOFF_MARKER_COUNTRY
         timeToLiveSeconds: 3600
      -  name: DAYOFF_MARKER_FIXEDHOLIDAY
         timeToLiveSeconds: 3600
      -  name: DAYOFF_MARKER_HOLIDAY
         timeToLiveSeconds: 3600
      -  name: DAYOFF_MARKER_STATE
         timeToLiveSeconds: 3600
      -  name: DAYOFF_MARKER_TAG
         timeToLiveSeconds: 3600

  dayoff-caches:
    caches:
      name_cache_city: DAYOFF_MARKER_CITY
      name_cache_country: DAYOFF_MARKER_COUNTRY
      name_cache_fixedholiday: DAYOFF_MARKER_FIXEDHOLIDAY
      name_cache_holiday: DAYOFF_MARKER_HOLIDAY
      name_cache_state: DAYOFF_MARKER_STATE
      name_cache_tag: DAYOFF_MARKER_TAG

application:
  view_response_json: true
  scheduling:
    request:
      create_date:
        initialDelayInMilliseconds: 180000
        find_request_create_date:
          fixedRateInMilliseconds: 180000
        run_request_create_date:
          fixedRateInMilliseconds: 120000
        batch:
          fixedRateInMilliseconds: 140000
    cache:
      initialDelayInMilliseconds: 180000
      clear:
        fixedRateInMilliseconds: 43200000
    holiday:
      initialDelayInMilliseconds: 180000
      create:
        fixedRateInMilliseconds: 180000
      update:
        fixedRateInMilliseconds: 180000

jdempotent:
  enable: true
  cache:
    redis:
      database: 1
      password: "str0ng_passw0rd"
      sentinelHostList: localhost
      sentinelPort: "26379"
      sentinelMasterName: "mymaster"
      expirationTimeHour: 2
      dialTimeoutSecond: 3
      readTimeoutSecond: 3
      writeTimeoutSecond: 3
      maxRetryCount: 3
      expireTimeoutHour: 3
