databaseChangeLog:
  - changeSet:
      id: insert_configuration
      author: System
      changes:
        - insert:
            dbms: 'mysql, postgresql'
            tableName: DOM_CONFIGURATION
            columns:
              - column:
                  name: CONFIGURATION_KEY
                  value: 'LIMIT_FORWARD_DAYS_YEARS'
              - column:
                  name: DESCRIPTION
                  value: 'Indicates the Limit for creating the days forward in years'
              - column:
                  name: CONFIGURATION_VALUE
                  value: '25'
              - column:
                  name: DEFAULT_VALUE
                  value: '25'
        - insert:
            dbms: 'mysql, postgresql'
            tableName: DOM_CONFIGURATION
            columns:
              - column:
                  name: CONFIGURATION_KEY
                  value: 'LIMIT_BACK_DAYS_YEARS'
              - column:
                  name: DESCRIPTION
                  value: 'Indicates the Limit to create the days back in years'
              - column:
                  name: CONFIGURATION_VALUE
                  value: '2'
              - column:
                  name: DEFAULT_VALUE
                  value: '2'
        - insert:
            dbms: 'mysql, postgresql'
            tableName: DOM_CONFIGURATION
            columns:
              - column:
                  name: CONFIGURATION_KEY
                  value: 'COUNTRY_DEFAULT'
              - column:
                  name: DESCRIPTION
                  value: 'Default Application Country'
              - column:
                  name: CONFIGURATION_VALUE
                  value: 'BRAZIL'
              - column:
                  name: DEFAULT_VALUE
                  value: 'BRAZIL'
