server:
  port: 9990

logging:
  exception-conversion-word:
  level:
    liquibase: INFO
    root: INFO

spring:
  cache:
    enable: true
    type: redis
    redis:
      key-prefix: 'api::'
      time-to-live: 12000000
  data:
    redis:
      repositories:
        enabled: false
      port: 26379
      password: '{cipher}5e954244f702180bb7165fdbf3d89aa7779da7ffa541934a2474dd6844d72065'
      sentinel:
        database: 0
        master: mymaster
        nodes: localhost
        password: '{cipher}5e954244f702180bb7165fdbf3d89aa7779da7ffa541934a2474dd6844d72065'
  
  datasource:
    url: jdbc:postgresql://localhost:5432/DayOff_Marker
    username: dayoff_marker_ADMIN
    password: pe&X=RwN&@!H7%mB
    hikari:
      connection-timeout: 5000
      idle-timeout: 150000
      max-lifetime: 300000
      minimum-idle: 10
      maximum-pool-size: 50
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
      names:
        - jobUpdateHoliday
        - jobCreatesDays
  task:
    scheduling:
      pool:
        size: 5

application:
  scheduling:
    day:
      create_date:
        find_request_create_date: "0 0 */1 * * *"
        run_request_create_date: "0 0 */3 * * *"
        run_create_day_batch: "0 0 */5 * * *"
        clear_day_batch: "0 0 */12 * * *"
    cache:
      clean: "0 0 */12 * * *"
    holiday:
      create:
        cron: "0 0 */1 * * *"
      batch:
        create:
          cron: "0 10 */1 * * *"
    tag:
      link:
        run_batch: "0 */10 * * * *"
      unlink:
        run_batch: "0 */10 * * * *"

insidesoftwares-cache:
  config:
    timeToLiveSeconds: 3600
    caches:
      -  name: DAYOFF_MARKER_CITY
         timeToLiveSeconds: 3600
      -  name: DAYOFF_MARKER_COUNTRY
         timeToLiveSeconds: 3600
      -  name: DAYOFF_MARKER_FIXEDHOLIDAY
         timeToLiveSeconds: 3600
      -  name: DAYOFF_MARKER_HOLIDAY
         timeToLiveSeconds: 3600
      -  name: DAYOFF_MARKER_STATE
         timeToLiveSeconds: 3600
      -  name: DAYOFF_MARKER_TAG
         timeToLiveSeconds: 3600
      -  name: DAYOFF_MARKER_WORKING
         timeToLiveSeconds: 3600
      -  name: DAYOFF_MARKER_DAY
         timeToLiveSeconds: 3600

dom:
  taskexecutor:
    corePoolSize: 500
    maxPoolSize: 1000
    queueCapacity: 1000
  job:
    chunk:
      requestToRunningUpdateHoliday: 2000
      requestsUpdateHoliday: 2000
      requestToFinalizedUpdateHoliday: 3000
      requestToRunningCreateDate: 2000
      requestsCreateDate: 2000
      requestToFinalizedCreateDate: 3000
      daysCreatedCreateDate: 3000
      dayBatchToProcessedCreateDate: 3000
      processDayBatch: 10000
      deleteAllDaysBatch: 10000
